**Table of contents**<a id='toc0_'></a>    
- [출처](#toc1_)    
- [제1유형_데이터 다루기](#toc2_)    
  - [데이터 불러오기](#toc2_1_)    
  - [유형1 - 데이터 타입(object, int, float, bool 등등)](#toc2_2_)    
  - [유형2 - 기초통계량(평균, 중앙값, 사분위수, IQR, 표준편차)](#toc2_3_)    
    - [1) 중심측도를 나타내는 값(평균, 중앙값, 최빈값)](#toc2_3_1_)    
    - [2) 산포도를 나타내는 값(분산, 표준편차, IQR, range(최대 - 최소) 등)](#toc2_3_2_)    
    - [3) 분포의 비대칭도](#toc2_3_3_)    
    - [4) 기타(합계, 절대값, 데이터 수 등)](#toc2_3_4_)    
    - [5) 그룹화하여 계산하기 (groupby 활용)](#toc2_3_5_)    
  - [유형3 - 데이터 인덱싱, 필터링, 정렬, 변경 등](#toc2_4_)    
  - [1) 데이터 인덱싱](#toc2_5_)    
  - [유형4 - 결측치, 이상치, 중복값 처리(제거 or 대체)](#toc2_6_)    
  - [유형5 - 데이터 스케일링(데이터 표준화, 데이터 정규화)](#toc2_7_)    
  - [유형6 - 데이터 합치기](#toc2_8_)    
  - [유형7 - 날짜/시간 데이터, index 다루기](#toc2_9_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

# <a id='toc1_'></a>[출처](#toc0_)
https://youtu.be/XTsTbqjJhjE?si=SuBUDiK0FK2XHthz

영상의 예제문제 따라하기

# <a id='toc2_'></a>[제1유형_데이터 다루기](#toc0_)

## <a id='toc2_1_'></a>[데이터 불러오기](#toc0_)

In [2]:
import pandas as pd
import numpy as np

In [3]:
mtcars_path = r'dataset\mtcars.csv'
df = pd.read_csv(mtcars_path)

df.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

## <a id='toc2_2_'></a>[유형1 - 데이터 타입(object, int, float, bool 등등)](#toc0_)

In [4]:
# 칼럼별 타입 확인

df.dtypes

model     object
mpg      float64
cyl        int64
disp     float64
hp         int64
drat     float64
wt       float64
qsec     float64
vs         int64
am         int64
gear       int64
carb       int64
dtype: object

In [5]:
# 데이터 타입 변경(1개)

df1 = df.copy()
df1 = df1.astype({'cyl':'object'})

print(df1.dtypes)

model     object
mpg      float64
cyl       object
disp     float64
hp         int64
drat     float64
wt       float64
qsec     float64
vs         int64
am         int64
gear       int64
carb       int64
dtype: object

In [6]:
# 데이터 타입 변경(2개)

df1 = df1.astype({'cyl':'int', 'gear':'object'})

print(df1.dtypes)

model     object
mpg      float64
cyl        int32
disp     float64
hp         int64
drat     float64
wt       float64
qsec     float64
vs         int64
am         int64
gear      object
carb       int64
dtype: object

In [7]:
df1['cyl'].value_counts()

cyl
8    14
4    11
6     7
Name: count, dtype: int64

## <a id='toc2_3_'></a>[유형2 - 기초통계량(평균, 중앙값, 사분위수, IQR, 표준편차)](#toc0_)

### <a id='toc2_3_1_'></a>[1) 중심측도를 나타내는 값(평균, 중앙값, 최빈값)](#toc0_)

In [8]:
df.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [9]:
df.shape # (행, 열)

(32, 12)

In [10]:
mpg_mean = df['mpg'].mean()         # 평균
mpg_median = df['mpg'].median()     # 중앙값
cyl_mode = df['cyl'].mode()         # 최빈값

print('평균값', mpg_mean)
print('중앙값', mpg_median)
print('-'*20)
print('최빈값', cyl_mode)
print('-'*20)
print('최빈값', cyl_mode[0])

평균값 20.090625000000003
중앙값 19.2
--------------------
최빈값 0    8
Name: cyl, dtype: int64
--------------------
최빈값 8

In [11]:
# 최빈값 체크

df['cyl'].value_counts()

cyl
8    14
4    11
6     7
Name: count, dtype: int64

### <a id='toc2_3_2_'></a>[2) 산포도를 나타내는 값(분산, 표준편차, IQR, range(최대 - 최소) 등)](#toc0_)

In [12]:
# 분산

mpg_var = df['mpg'].var()

print(mpg_var)

36.32410282258065

In [13]:
# 표준편차

import math

mpg_std = df['mpg'].std()

print(mpg_std)
print(math.sqrt(mpg_var))

6.026948052089105
6.026948052089105

In [14]:
# IQR

Q1 = df['mpg'].quantile(.25)
Q3 = df['mpg'].quantile(.75)

IQR = Q3 - Q1

print(IQR)

7.375

In [15]:
# 범위

mpg_max = df['mpg'].max()
mpg_min = df['mpg'].min()

mpg_range = mpg_max - mpg_min

print(mpg_range)

23.5

### <a id='toc2_3_3_'></a>[3) 분포의 비대칭도](#toc0_)

In [16]:
# 왜도(Skewness): 분포의 비대칭 정도를 나타냄 (0이면 대칭, 음수면 왼쪽, 양수면 오른쪽으로 치우침)

mpg_skew = df['mpg'].skew()

print(mpg_skew)

0.6723771376290805

In [17]:
# 첨도(Kurtosis): 분포의 뾰족한 정도를 나타냄 (정규분포의 첨도는 3, 3보다 크면 뾰족, 작으면 평평)

mpg_kurt = df['mpg'].kurt()

print(mpg_kurt)

-0.0220062914240855

### <a id='toc2_3_4_'></a>[4) 기타(합계, 절대값, 데이터 수 등)](#toc0_)

In [18]:
# 합계

mpg_sum = df['mpg'].sum()

print(mpg_sum)

642.9000000000001

In [19]:
# 절대값

print(abs(1-3))

2

In [20]:
# 데이터 수

len(df['mpg'])

32

### <a id='toc2_3_5_'></a>[5) 그룹화하여 계산하기 (groupby 활용)](#toc0_)

In [21]:
# species별로 각 변수의 평균 구해보기

import seaborn as sns

iris = sns.load_dataset('iris')
display(iris)
iris.groupby('species').mean()

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.428         1.462        0.246
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [22]:
iris.groupby('species').median()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa               5.0          3.4          1.50          0.2
versicolor           5.9          2.8          4.35          1.3
virginica            6.5          3.0          5.55          2.0

## <a id='toc2_4_'></a>[유형3 - 데이터 인덱싱, 필터링, 정렬, 변경 등](#toc0_)

In [23]:
df.head(7)

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4

### <a id='toc2_5_'></a>[1) 데이터 인덱싱(loc, iloc)](#toc0_) ※loc 인덱스 주의

In [24]:
# 행,열 인덱싱

df.loc[3,'mpg']

21.4

In [25]:
# 열만 인덱싱

df.loc[:, 'mpg'].head()

0    21.0
1    21.0
2    22.8
3    21.4
4    18.7
Name: mpg, dtype: float64

In [ ]:
# 다중 인덱싱

df.loc[0:3, ['mpg', 'cyl', 'disp']]     # ※ loc 인덱스는 뒤 숫자까지 포함! (0:3 == 0,1,2,3)

    mpg  cyl   disp
0  21.0    6  160.0
1  21.0    6  160.0
2  22.8    4  108.0
3  21.4    6  258.0

## <a id='toc2_6_'></a>[유형4 - 결측치, 이상치, 중복값 처리(제거 or 대체)](#toc0_)

## <a id='toc2_7_'></a>[유형5 - 데이터 스케일링(데이터 표준화, 데이터 정규화)](#toc0_)

## <a id='toc2_8_'></a>[유형6 - 데이터 합치기](#toc0_)


## <a id='toc2_9_'></a>[유형7 - 날짜/시간 데이터, index 다루기](#toc0_)